Update build-instructions.md: clarify where to use -DTARGET_i386=OFF flag.
darlinghq/darling-docs pull request #72
Opened 2024-02-23 21:40 UTC by wyattscarpenter

2024-02-24 02:26 UTC, CuriousTommy requested changes
The `during configuration` part is meant to imply that you should use `cmake`, but I also understand that this might not be obvious for someone who isn't familiar with `make`/`cmake`.

For consistency, I would also update the following to make it more clear that you should use `cmake`:
https://github.com/darlinghq/darling-docs/blob/99f2a324b82fb5191f657f78d99b6f67e508ee98/src/build-instructions.md?plain=1#L181
https://github.com/darlinghq/darling-docs/blob/99f2a324b82fb5191f657f78d99b6f67e508ee98/src/build-instructions.md?plain=1#L196
https://github.com/darlinghq/darling-docs/blob/99f2a324b82fb5191f657f78d99b6f67e508ee98/src/build-instructions.md?plain=1#L200
https://github.com/darlinghq/darling-docs/blob/99f2a324b82fb5191f657f78d99b6f67e508ee98/src/build-instructions.md?plain=1#L224

2024-02-24 02:26 UTC, CuriousTommy commented on src/build-instructions.md
>  want to build only the 64-bit components, use `-DTARGET_i386=OFF` during configuration to disable building the 32-bit components.
I would word it like this instead
```suggestion
want to build only the 64-bit components, append `-DTARGET_i386=OFF` when you run `cmake` to disable building the 32-bit components.
```

2024-03-30 02:45 UTC, wyattscarpenter commented
I incorporated your change and took at stab at the other changes, which I agree would be good to clarify.

Notably, I don't actually know how COMPONENTS works, because I don't know cmake, so I guessed.

2024-03-30 02:53 UTC, CuriousTommy approved these changes
LGTM

2024-03-30 02:53 UTC, merged

2024-03-30 02:54 UTC, CuriousTommy commented
Thank you for your contribution!