Added paragraph about SSE3 support to build-instructions.md.
darlinghq/darling-docs pull request #76
Opened 2024-06-27 22:25 UTC by osxaudio

### What
Added a small paragraph on how to fix missing SSE3 Support by installing the opemu-linux kernel module.
### Why
I just want to save others from going through these two issues: https://github.com/darlinghq/darling/issues/776, https://github.com/darlinghq/darling/issues/882, before arriving at https://github.com/darlinghq/darling/issues/1497 and figuring out the solution by @Mabbs works for them too.
### Why like this
Yes build instructions might not be the perfectly correct page for this paragraph, but I didn't find any other “Known Issues Section” and the ZFS problem is also handled here, therefore I think it is not too out of place
### Open questions/concerns
Only question, should I add a warning about installing some random kernel module from GitHub ?

2024-06-29 15:13 UTC, CuriousTommy commented on src/build-instructions.md
> +```
I have mixed feelings about including build instructions for projects that the Darling team does not manage. Ideally, you should submit a PR request to the `opemu-linux` to add build instructions.

With that being said, it's looks like that project is no longer in active development.

2024-06-29 15:26 UTC, CuriousTommy requested changes

2024-06-29 15:26 UTC, CuriousTommy commented on src/build-instructions.md
> +user$ sudo darling shell
I don't like the implication of including a command like `sudo darling shell` in the wiki. I don't want the wiki to imply that this is an okay thing to do.

I recommend removing the `user$ darling shell` and `user$ sudo darling shell` part.

2026-01-07 17:44 UTC, hamishmb commented on src/build-instructions.md
> +```
Yeah, that project looks defunct now, and I imagine it won't build against current kernel versions any more most likely. Noting that SSE3 support is required might still be a good thing to do though? Shall I make another PR for that?

2026-01-07 20:24 UTC, CuriousTommy commented on src/build-instructions.md
> +```
> Noting that SSE3 support is required might still be a good thing to do though? Shall I make another PR for that?

Go for it! I'll close this PR.

2026-01-07 20:24 UTC, closed without merging