Add instruction for Rocky Linux 9
darlinghq/darling-docs pull request #78
Opened 2024-12-30 00:37 UTC by hisergiorojas

#77

2024-12-31 04:09 UTC, CuriousTommy requested changes

2024-12-31 04:09 UTC, CuriousTommy commented on src/build-instructions.md
> +sudo dnf update
IMO, it's better to direct users to the official guide.

Such as this one: https://rpmfusion.org/Configuration

2024-12-31 04:09 UTC, CuriousTommy commented on src/build-instructions.md
> +sudo dnf update
This is question rather then a request, but what dependencies are need from the `crb` repo?

2025-01-01 17:29 UTC, hisergiorojas commented on src/build-instructions.md
> +sudo dnf update
fuse-devel 
giflib-devel 
libxkbfile-devel 
libavcodec-free-devel

2025-01-04 18:20 UTC, hisergiorojas commented on src/build-instructions.md
> +sudo dnf update
I updated the build instruction.

2025-01-04 18:40 UTC, CuriousTommy approved these changes
Looks good to me!

2025-01-04 18:40 UTC, merged

2025-01-04 18:41 UTC, CuriousTommy commented
Thank you for your contribution!